services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8443"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8443
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      KEY_STORE_PATH: ${KEY_STORE_PATH}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      KEY_ALIAS: ${KEY_ALIAS}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgData:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  pgData:

networks:
  app-network:
    driver: bridge
